app_name: Agentic-Evals
version: 1.0.0
data_generation:
  num_of_queries: all
  query_key: query
  input_path: datasets
  input_file: ground_truth.json
  output_path: results
  output_file: agent_predicted.json
data_transformation:
  input_path: results
  input_file: agent_predicted.json
  output_path: results
  output_file_json: agent_predicted_transformed.json
  output_file_jsonl: agent_predicted_transformed.jsonl
  schema_path: config
  schema_file: schema.json 
evaluation:
  input_path: results
  input_file: agent_predicted_transformed.jsonl
  output_path: results
  output_file: evaluation_results.json
  eval_name: Function_call_evaluation
report:
  input_path: results
  input_file: evaluation_results.json
  output_path: reports
  output_file: evaluation_report.html
  template_path: template
  template_file: report_template.html
pipeline:
  steps:
    - data_generation
    - data_transformation
    - evaluation
    - reporting